
---
apiVersion: v1
kind: Namespace
metadata:
  name: anotherapp-build
  labels:
    app : anotherapp
    team: group:default/devgroup1
    build-namespace: anotherapp-build
    size: small
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: anotherapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: anotherapp-dev
  labels:
    app : anotherapp
    team: group:default/devgroup1
    build-namespace: anotherapp-build
    size: small
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: anotherapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: anotherapp-qa
  labels:
    app : anotherapp
    team: group:default/devgroup1
    build-namespace: anotherapp-build
    size: small
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: anotherapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: anotherapp-prod
  labels:
    app : anotherapp
    team: group:default/devgroup1
    build-namespace: anotherapp-build
    size: small
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: anotherapp-build
